# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example-Objc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'MyChat', :path => '.'
  pod 'QiscusCore'

    # 3rd party
  pod 'SDWebImage', '~> 4.4.2'
  pod 'SimpleImageViewer', :git => 'https://github.com/aFrogleap/SimpleImageViewer'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'UICircularProgressRing'
end
